// Generated by CoffeeScript 2.5.1
import upnp from './index.js';

(async() => {
  var soap;
  soap = (await upnp());
  if (!soap) {
    console.log("UPNP not available");
    return;
  }
  // mapPort(protocol,internal,external,duration=0,description="")
  await soap.mapPort("UDP", 8080, 8080, 0, "upnp test");
  return console.log((await soap.map()));
})();

//# sourceMappingURL=index_test.js.map
