// Generated by CoffeeScript 2.5.1
import {
  Upnp
} from './deps.js';

(async() => {
  var upnp;
  upnp = (await Upnp());
  if (!upnp) {
    console.log("UPNP not available");
    return;
  }
  // mapPort(protocol,internal,external,duration=0,description="")
  await upnp.mapPort("UDP", 8080, 8080, 0, "upnp test");
  return console.log((await upnp.map()));
})();

//# sourceMappingURL=index_test.js.map
