// Generated by CoffeeScript 2.5.1
import {
  Upnp
} from './deps.js';

export default () => {
  var addr, port, udp;
  udp = Deno.listenDatagram({
    port: 0,
    transport: "udp",
    hostname: "0.0.0.0"
  });
  ({addr} = udp);
  ({port} = addr);
  console.log(`listen on ${port}`);
  return queueMicrotask(async() => {
    var NewExternalPort, NewInternalClient, NewInternalPort, NewProtocol, ip, ref, results, upnp, x;
    upnp = (await Upnp());
    if (!upnp) {
      console.log("UPNP not available");
      return;
    }
    // mapPort(protocol,internal,external,duration=0,description="")
    ip = (await upnp.mapPort("UDP", port, port, 0, "upnp test"));
    ref = (await upnp.map());
    results = [];
    for (x of ref) {
      ({NewInternalClient, NewExternalPort, NewInternalPort, NewProtocol} = x);
      if (NewProtocol !== "UDP") {
        continue;
      }
      if (NewInternalClient !== ip) {
        continue;
      }
      results.push(console.log(NewExternalPort, NewInternalPort));
    }
    return results;
  });
};

//# sourceMappingURL=index.js.map
