// Generated by CoffeeScript 2.5.1
var local_ip;

export default local_ip = async(hostname, port) => {
  var socket;
  // https://github.com/denoland/deno/issues/10519
  // Deno.connect not support transport:"udp"
  socket = (await Deno.connect({port, hostname}));
  socket.close();
  return socket.localAddr.hostname;
};

//# sourceMappingURL=local_ip.js.map
