// Generated by CoffeeScript 2.5.1
export default async(udp) => {
  var msg, remote, results;
  console.log((await udp.send(new Uint8Array([]), {
    hostname: "54.177.127.37",
    port: 17944,
    transport: "udp"
  })));
  results = [];
  while (true) {
    [msg, remote] = (await udp.receive(new Uint8Array(1472)));
    console.log(remote);
    console.log(msg);
    console.log(msg.length);
    results.push(console.log(""));
  }
  return results;
};

//# sourceMappingURL=udp.js.map
