// Generated by CoffeeScript 2.5.1
import {
  Upnp
} from './deps.js';

export default async(port, transport) => {
  var NewExternalPort, NewInternalClient, NewInternalPort, NewProtocol, ip, ref, results, upnp, x;
  upnp = (await Upnp());
  if (!upnp) {
    console.log("UPNP not available");
    return;
  }
  // mapPort(protocol,internal,external,duration=0,description="")
  ip = (await upnp.mapPort("UDP", port, port, 0, "https://rmw.link"));
  ref = upnp.map();
  results = [];
  for await (x of ref) {
    ({NewInternalClient, NewExternalPort, NewInternalPort, NewProtocol} = x);
    if (NewProtocol.toLowerCase() !== transport) {
      continue;
    }
    if (NewInternalClient !== ip) {
      continue;
    }
    if (NewInternalPort === port) {
      console.log("upnp", NewExternalPort, "=>", port);
      break;
    } else {
      results.push(void 0);
    }
  }
  return results;
};

//# sourceMappingURL=upnp.js.map
